project_id = "gfmhhnynyxvmekhvytgg"

[functions.create-checkout-session]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false

[functions.newsletter-signup]
verify_jwt = false

[functions.send-weekly-campaign]
verify_jwt = false

[functions.send-ab-test]
verify_jwt = false

[functions.select-ab-winner]
verify_jwt = false

[functions.send-ab-winner]
verify_jwt = false

[functions.update-engagement-scores]
verify_jwt = false

[functions.populate-campaign-content]
verify_jwt = false